# Generated by Django 5.2 on 2025-04-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_products_p_offer_products_p_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='p_offer',
        ),
        migrations.RemoveField(
            model_name='products',
            name='p_trending',
        ),
        migrations.AddField(
            model_name='products',
            name='p_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='products',
            name='totalamount',
            field=models.IntegerField(default=0),
        ),
    ]
