# Generated by Django 5.2 on 2025-04-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_products_p_offer_remove_products_p_trending_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('p_images', models.ImageField(default='default.png', upload_to='uploads')),
                ('p_quantity', models.IntegerField(default=1)),
                ('totalamount', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='p_quantity',
        ),
        migrations.RemoveField(
            model_name='products',
            name='totalamount',
        ),
        migrations.AddField(
            model_name='products',
            name='p_offer',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='p_trending',
            field=models.BooleanField(default=0),
        ),
    ]
